### ISSUE TITLE
Update BioMedQuery to be v0.7 & v1.0 compatible

### ISSUE THREAD

**Issue by mcmcgrath13** [JuliaHealth/BioMedQuery.jl#36]

**Comment by mirestrepo** [comment]
😅 Thanks for self-assigning this!

**Comment by mcmcgrath13** [comment]
v0.7 compatible version has a PR in progress with METADATA

**Comment by mcmcgrath13** [comment]
@mirestrepo is it okay to uncomment the travis tests and examples?
