### ISSUE TITLE
Option of using DataFrame as a "backend" 

### ISSUE THREAD

**Issue by paulstey** [JuliaHealth/BioMedQuery.jl#5]
In addition to the current MySQL and SQLite backends, it would be nice to give users the option of using a `DataFrame` as a "backend". This removes the dependency on a relational database and makes sense for smaller queries where we would prefer to do everything in memory.

**Comment by mcmcgrath13** [comment]
This capability is being added as part of the medline loader enhancements - though additional work may be needed to make it a backend option for the current processes.
