### ISSUE TITLE
Pkg.build(BioMedQuery) error on Julia 0.6.4 

### ISSUE THREAD

**Issue by anthonyagudelox3** [JuliaHealth/BioMedQuery.jl#58]
Hello,

I am having an issue when I attempting to build BioMedQuery on Julia 0.6.4 and get the following build error with one of BioMedQuery's dependencies SQLite. I am running the Julia on windows 10 machine.

`julia> Pkg.build("BioMedQuery")
INFO: Building CodecZlib
INFO: Building LibCURL
INFO: Building LightXML
INFO: Building MbedTLS
INFO: Building SpecialFunctions
INFO: Building DecFP
INFO: Building MySQL
INFO: Building Gumbo
INFO: Building WinRPM
INFO: Downloading https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_Leap_42.2/repodata/repomd.xml
INFO: Downloading https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_Leap_42.2/repodata/repomd.xml
INFO: Building SQLite
INFO: Updating WinRPM package list
INFO: Downloading https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_Leap_42.2/repodata/repomd.xml
INFO: Downloading https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_Leap_42.2/repodata/repomd.xml
INFO: Nothing to do
===================================================[ ERROR: SQLite ]====================================================

LoadError: Provider BinDeps.PackageManager failed to satisfy dependency sqlite3_lib
while loading C:\Users\Thor.julia\v0.6\SQLite\deps\build.jl, in expression starting on line 19

========================================================================================================================

====================================================[ BUILD ERRORS ]====================================================

WARNING: SQLite had build errors.

packages with build errors remain installed in C:\Users\Thor.julia\v0.6
build the package(s) and all dependencies with Pkg.build("SQLite")
build a single package by running its deps/build.jl script
========================================================================================================================

julia>`

**Comment by DilumAluthge** [comment]
Hi @anthonyagudelox3, thanks for submitting this issue.

Unfortunately, Julia 0.6 is no longer supported. I would recommend that you transition to Julia 0.7 and then subsequently to Julia 1.0.

If you encounter an error building BioMedQuery.jl on Julia 0.7 and/or Julia 1.0, please open a new issue.
